Homework6
AndreReen/AndreiReentovich pull request #7
Opened 2021-05-17 20:51 UTC by AndreReen

HW6 ready for review

2021-05-21 13:29 UTC, shoggy requested changes
putting annotation and variable definition in one line makes code not readable

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw4/potest/TestExerciseSteps2.java
Files from previous HW should not present in this PR

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/Actions/Actions.java
> +    }
the method should accept some Entity as an argument

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/Actions/CreateDataProvider.java
> +package ru.training.at.hw6.Actions;
The class should be in some other package (actions is a wrong place)

\+ package name should not contain capital cased letters

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/PageObjects/JdiSite.java
> +    @UI(".form") public static MetalsAndColorsForm macForm;
not obvious name

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/PageObjects/MetalsAndColorsPage.java
> +    public static Text vegRes;
This approach can be simplified by using List

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/entities/TestValues.java
> +public class TestValues {
The class name should reflect its purpose

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +public class MetalsAndColorsForm extends Form<MetalsAndColorsForm> {
This class should extend Form with DataClass
For the example check `LoginForm`

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +    }
This method can be overridden with DataClass as argument

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +    }
Get rid of this method in favor of `submit` override

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +public class TheTest implements TestsInit {
Test class name should reflect its purpose

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +    public void MetalsColorsFormFillTest(TestValues data) {
1. Code convention breaker
1.  What do you mean by `data` argument name?

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/Actions/CreateDataProvider.java
> +public class CreateDataProvider {
Name should have some meaning

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        Actions.logout();
Multiple styles (actions, page object actions straight calls and some method inside test class `verifyResults`)

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        headerMenu.select("METALS & COLORS");
Pure string is not a good choice, consider use of constants of Enum

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        Assert.assertEquals(vegRes.getText(), vegExp);
This approach can be simplified, compare two collections
`List<> expected, List<> actualValuesFromElement`

2021-05-21 13:29 UTC, shoggy commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        String vegExp = "Vegetables: " + vegBuild.substring(1, vegBuild.length() - 1);
This method should not be in this class, it breaks one of the design principles

2021-05-21 13:37 UTC, shoggy commented
Please modify checkstyle settings, copy-paste it from [example](https://github.com/DmitryKhodakovsky/epam-test-auto-spring-2021/blob/master/pom.xml) (plugin definition and versions)

2021-05-21 14:29 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/Actions/CreateDataProvider.java
> +package ru.training.at.hw6.Actions;
Moved class to data_providers package.
Updated package names to meet naming conventions.

2021-05-21 14:29 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/Actions/Actions.java
> +    }
Updated

2021-05-21 14:32 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/PageObjects/JdiSite.java
> +    @UI(".form") public static MetalsAndColorsForm macForm;
Updated name to be more clear =  metalAndColorForm

2021-05-21 14:43 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/PageObjects/MetalsAndColorsPage.java
> +    public static Text vegRes;
Implemented list of Webelements

2021-05-21 14:44 UTC, AndreReen commented on src/test/java/ru/training/at/hw4/potest/TestExerciseSteps2.java
Crossover from refactoring previous HW

2021-05-21 14:49 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/entities/TestValues.java
> +public class TestValues {
Updated

2021-05-21 14:49 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +public class MetalsAndColorsForm extends Form<MetalsAndColorsForm> {
Fixed

2021-05-21 14:59 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +    }
Done

2021-05-21 15:05 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +public class TheTest implements TestsInit {
Updated

2021-05-21 15:05 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/Actions/CreateDataProvider.java
> +public class CreateDataProvider {
Updated

2021-05-21 15:10 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        headerMenu.select("METALS & COLORS");
Created enum class with header menu items

2021-05-21 16:16 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        String vegExp = "Vegetables: " + vegBuild.substring(1, vegBuild.length() - 1);
Made this method a part of MetalsAndColors Entity

2021-05-21 16:16 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        Assert.assertEquals(vegRes.getText(), vegExp);
Implemented

2021-05-21 16:16 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        headerMenu.select("METALS & COLORS");
Created enum for  header menu items.

2021-05-21 16:17 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/Actions/CreateDataProvider.java
> +public class CreateDataProvider {
Updated to DataProviderForMetalAndColorForm.java

2021-05-21 16:17 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/PageObjects/MetalsAndColorsPage.java
> +    public static Text vegRes;
Implemented

2021-05-21 16:18 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/PageObjects/JdiSite.java
> +    @UI(".form") public static MetalsAndColorsForm macForm;
Updated to metalAndColorForm

2021-05-21 17:58 UTC, AndreReen commented on src/test/java/ru/training/at/hw6/tests/TheTest.java
> +        Actions.logout();
Refactored to Actions style

2021-05-24 10:48 UTC, shoggy approved these changes

2021-05-24 15:32 UTC, merged